spring:
  application:
    name: pensioner-auth
  jackson:
    default-property-inclusion: NON_NULL
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: 'jdbc:h2:mem:testdb;INIT=CREATE SCHEMA IF NOT EXISTS test_db'
    driverClassName: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-ui
server:
  port: '8080'
eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka/'
  instance:
    prefer-ip-address: true
    hostname: localhost
jwt:
  secret: secretkey
  token:
    validity: '18000'
