spring:
  application:
    name: process-pension
  config:
    import: 'optional:configserver:http://localhost:8888/'
server:
  port: '8100'
eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka/'
  instance:
    prefer-ip-address: true