spring:
  application:
    name: pension-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowercaseServiceId: true
  jackson:
    default-property-inclusion: NON_NULL
server-port: '8765'
eureka:
  client:
    service-url:
      default-zone: 'http://localhost:8761/eureka'
  instance:
    prefer-ip-address: true
jwt:
  secret: secretkey
  token:
    validity: '18000'